call _reposJar json-lib-2.4-jdk15.jar     net.sf.json-lib json-lib 2.3
call _reposJar gt-api-2.6.0.jar           org.geotools gt-api 2.6.0
call _reposJar gt-main-2.6.0.jar          org.geotools gt-main 2.6.0
call _reposJar gt-metadata-2.6.0.jar      org.geotools gt-metadata 2.6.0
call _reposJar gt-referencing-2.6.0.jar   org.geotools gt-referencing 2.6.0
call _reposJar gt-shapefile-2.6.0.jar     org.geotools gt-shapefile 2.6.0
call _reposJar jts-1.9.jar                vividsolutions jts 1.9
call _reposJar mvclient.jar               oracle mvclient 1.0
call _reposJar ordim.jar                  oracle ordim 1.0
call _reposJar ordimimg.jar               oracle ordimimg 1.0
call _reposJar sdoapi.jar          		  oracle sdoapi 1.0
call _reposJar sdogcdr.jar                oracle sdogcdr 1.0
call _reposJar sdogr.jar                  oracle sdogr 1.0
call _reposJar sdondme.jar                oracle sdondme 1.0
call _reposJar sdondmx.jar                oracle sdondmx 1.0
call _reposJar sdonm.jar                  oracle sdonm 1.0
call _reposJar sdordf.jar                 oracle sdordf 1.0
call _reposJar sdoshp.jar                 oracle sdoshp 1.0
call _reposJar sdotopo.jar                oracle sdotopo 1.0
call _reposJar sdotype.jar                oracle sdotype 1.0
call _reposJar sdoutl.jar                 oracle sdoutl 1.0
call _reposJar sdovis.jar                 oracle sdovis 1.0
call _reposJar sdowfscs.jar               oracle sdowfscs 1.0
call _reposJar sdowshandlerols.jar        oracle sdowshandlerols 1.0
call _reposJar sdowshandlers.jar          oracle sdowshandlers 1.0
call _reposJar sdowspool.jar              oracle sdowspool 1.0
call _reposJar sqljdbc4.jar               com.microsoft.sqlserver sqljdbc4 4.0
call _reposJar xml.jar                    oracle xml 1.0
call _reposJar xmlparserv2.jar            oracle xmlparserv2 1.0
call _reposJar xmlparserv2.jar            oracle xmlparserv2 1.0